"""Caricamento e conservazione dei documenti della knowledge base."""

from app.knowledge.configuration import (
    DEFAULT_KNOWLEDGE_STORAGE_DIRECTORY,
    KNOWLEDGE_STORAGE_DIRECTORY_ENV,
    get_knowledge_storage_directory,
)
from app.knowledge.uploads import (
    ALLOWED_DOCUMENT_EXTENSIONS,
    MAX_DOCUMENT_SIZE_BYTES,
    KnowledgeDocumentPersistenceError,
    KnowledgeDocumentValidationError,
    store_knowledge_document,
)
from app.knowledge.extraction import (
    EXTRACTION_FAILED,
    EXTRACTION_PENDING,
    EXTRACTION_READY,
    MAX_SEGMENT_CHARACTERS,
    ExtractionResult,
    KnowledgeDocumentProcessingError,
    build_segment_drafts,
    process_knowledge_document,
)
from app.knowledge.management import (
    DocumentDeletionResult,
    KnowledgeDocumentDeletionError,
    KnowledgeDocumentNotFoundError,
    delete_knowledge_document,
)
from app.knowledge.indexing import (
    INDEX_FAILED,
    INDEX_PENDING,
    INDEX_READY,
    IndexingResult,
    KnowledgeIndexingError,
    KnowledgeSearchError,
    KnowledgeSearchResult,
    KnowledgeSearchValidationError,
    index_knowledge_document,
    search_knowledge,
)
from app.knowledge.solutions import (
    MIN_SOLUTION_SOURCE_SCORE,
    NO_SOLUTION_SOURCES_MESSAGE,
    SOLUTION_GENERATED,
    SOLUTION_INVALID_RESPONSE,
    SOLUTION_PENDING,
    SOLUTION_UNAVAILABLE,
    WEAK_SOLUTION_SOURCES_MESSAGE,
    AIProposedSourcedSolution,
    TicketSolutionPersistenceError,
    TicketSolutionSourceView,
    generate_ticket_solution,
    list_ticket_solution_sources,
    suggest_sourced_solution,
)

__all__ = [
    "ALLOWED_DOCUMENT_EXTENSIONS",
    "DEFAULT_KNOWLEDGE_STORAGE_DIRECTORY",
    "KNOWLEDGE_STORAGE_DIRECTORY_ENV",
    "MAX_DOCUMENT_SIZE_BYTES",
    "MAX_SEGMENT_CHARACTERS",
    "EXTRACTION_FAILED",
    "EXTRACTION_PENDING",
    "EXTRACTION_READY",
    "ExtractionResult",
    "INDEX_FAILED",
    "INDEX_PENDING",
    "INDEX_READY",
    "IndexingResult",
    "KnowledgeDocumentPersistenceError",
    "KnowledgeDocumentProcessingError",
    "KnowledgeDocumentValidationError",
    "KnowledgeIndexingError",
    "KnowledgeSearchError",
    "KnowledgeSearchResult",
    "KnowledgeSearchValidationError",
    "MIN_SOLUTION_SOURCE_SCORE",
    "NO_SOLUTION_SOURCES_MESSAGE",
    "SOLUTION_GENERATED",
    "SOLUTION_INVALID_RESPONSE",
    "SOLUTION_PENDING",
    "SOLUTION_UNAVAILABLE",
    "WEAK_SOLUTION_SOURCES_MESSAGE",
    "AIProposedSourcedSolution",
    "TicketSolutionPersistenceError",
    "TicketSolutionSourceView",
    "get_knowledge_storage_directory",
    "build_segment_drafts",
    "process_knowledge_document",
    "DocumentDeletionResult",
    "KnowledgeDocumentDeletionError",
    "KnowledgeDocumentNotFoundError",
    "delete_knowledge_document",
    "index_knowledge_document",
    "search_knowledge",
    "generate_ticket_solution",
    "list_ticket_solution_sources",
    "suggest_sourced_solution",
    "store_knowledge_document",
]
